version: '3.7'

services:

  web:
    image: $IMAGE_TAG
    build:
      context: .
      args:
        APP_NAME: ${APP_NAME}
        ENVIRONMENT: ${ENVIRONMENT}
    container_name: ${APP_NAME}_${ENVIRONMENT}_web
    environment:
      - APP_NAME
      - SQL_ENGINE
      - SQL_DATABASE
      - SQL_USER
      - SQL_PASSWORD
      - SQL_HOST
      - SQL_PORT
      - DJANGO_SETTINGS_MODULE
      - VIRTUAL_HOST
      - VIRTUAL_PORT
      - SECRET_KEY
      - LINK_FORUM
    volumes:
      - /opt/nginxproxy/assets/${APP_NAME}:/assets
      - /opt/nginxproxy/vhost.d:/vhostd

    expose:
      - ${VIRTUAL_PORT}

    networks:
      - nginx-proxy
      - default

    command: bash -c "cp ./vhostd.conf /vhostd/${VIRTUAL_HOST} && python manage.py collectstatic --noinput && gunicorn ${APP_NAME}.wsgi -t 7200 -w 3 -b 0.0.0.0:${VIRTUAL_PORT}"

    depends_on:
      - db

  db:
    image: postgres:12-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=${SQL_USER}
      - POSTGRES_PASSWORD=${SQL_PASSWORD}
      - POSTGRES_DB=${SQL_DATABASE}
    networks:
      - default

volumes:
  postgres_data:

networks:
  nginx-proxy:
    external: true
  default:
    name: "${APP_NAME}_${ENVIRONMENT}_default"
