# Generated by Django 3.1.7 on 2021-07-07 20:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('municipios', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Organizacao',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cadastro_aprovacao', models.BooleanField(default=False, null=True, verbose_name='Autorizar Cadastro/Atualização')),
                ('nome', models.CharField(max_length=100, unique=True, verbose_name='Nome da Organização')),
                ('website_organizacao', models.CharField(max_length=100, verbose_name='Site da Organização')),
                ('pessoa_contato', models.CharField(max_length=100, verbose_name='Pessoa de contato para a rede Adapta Brasil MCTI')),
                ('telefone_contato', models.CharField(max_length=14, verbose_name='Telefone da Organização')),
                ('email_contato', models.EmailField(max_length=254, verbose_name='Email da Organização')),
                ('natureza_organizacao', models.SmallIntegerField(choices=[(1, 'Organização Pública'), (2, 'Organização Privada'), (3, 'Organização Público-Privada'), (4, 'Organização Não Governamental'), (5, 'Pessoa Física')], verbose_name='Natureza da Organização')),
                ('logo', models.ImageField(blank=True, upload_to='', verbose_name='Logo')),
                ('sobre_organizacao', models.TextField(blank=True, max_length=1000, verbose_name='Sobre a Organização')),
                ('observacao_adicional', models.TextField(blank=True, max_length=1000, verbose_name='Informações Adicionais')),
                ('municipio', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='municipios', to='municipios.municipio', verbose_name='Município')),
            ],
            options={
                'verbose_name': 'Organização',
                'verbose_name_plural': 'Organizações',
            },
        ),
        migrations.CreateModel(
            name='OrganizacaoSitemap',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='SetorEconomico',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, verbose_name='Nome do Setor Economico')),
            ],
            options={
                'verbose_name': 'Setor Econômico',
                'verbose_name_plural': 'Setores Econômicos',
            },
        ),
        migrations.CreateModel(
            name='TipoOrganizacao',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, verbose_name='Nome do Tipo da Organização')),
            ],
            options={
                'verbose_name': 'Tipo de Organização',
                'verbose_name_plural': 'Tipos de Organização',
            },
        ),
        migrations.CreateModel(
            name='TipoProduto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, verbose_name='Nome do Tipo do Produto')),
            ],
            options={
                'verbose_name': 'Tipo do Produto',
                'verbose_name_plural': 'Tipos dos Produtos',
            },
        ),
        migrations.CreateModel(
            name='OrganizacaoTipoProduto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('detalhes_servico', models.TextField(verbose_name='Detalhes dos Serviços')),
                ('organizacao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='guia_servs_clima.organizacao')),
                ('tipo_produto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='guia_servs_clima.tipoproduto')),
            ],
            options={
                'unique_together': {('tipo_produto', 'organizacao')},
            },
        ),
        migrations.CreateModel(
            name='OrganizacaoTipoOrganizacao',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('organizacao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='guia_servs_clima.organizacao')),
                ('tipo_organizacao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='guia_servs_clima.tipoorganizacao')),
            ],
        ),
        migrations.CreateModel(
            name='OrganizacaoSetorEconomico',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('organizacao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='guia_servs_clima.organizacao')),
                ('setor_economico', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='guia_servs_clima.setoreconomico')),
            ],
            options={
                'unique_together': {('setor_economico', 'organizacao')},
            },
        ),
        migrations.AddField(
            model_name='organizacao',
            name='setores_economicos',
            field=models.ManyToManyField(blank=True, through='guia_servs_clima.OrganizacaoSetorEconomico', to='guia_servs_clima.SetorEconomico'),
        ),
        migrations.AddField(
            model_name='organizacao',
            name='tipos_organizacao',
            field=models.ManyToManyField(blank=True, through='guia_servs_clima.OrganizacaoTipoOrganizacao', to='guia_servs_clima.TipoOrganizacao'),
        ),
        migrations.AddField(
            model_name='organizacao',
            name='tipos_produto',
            field=models.ManyToManyField(blank=True, through='guia_servs_clima.OrganizacaoTipoProduto', to='guia_servs_clima.TipoProduto'),
        ),
    ]
