# Generated by Django 3.1.7 on 2021-07-28 16:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('guia_servs_clima', '0002_auto_20210721_1424'),
    ]

    operations = [
        migrations.DeleteModel(
            name='OrganizacaoSitemap',
        ),
    ]
