# Generated by Django 3.1.7 on 2021-08-17 20:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guia_servs_clima', '0004_auto_20210811_1757'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organizacao',
            name='setores_economicos',
            field=models.ManyToManyField(through='guia_servs_clima.OrganizacaoSetorEconomico', to='guia_servs_clima.SetorEconomico'),
        ),
        migrations.AlterField(
            model_name='organizacao',
            name='tipos_organizacao',
            field=models.ManyToManyField(through='guia_servs_clima.OrganizacaoTipoOrganizacao', to='guia_servs_clima.TipoOrganizacao'),
        ),
        migrations.AlterField(
            model_name='organizacao',
            name='tipos_pagamento',
            field=models.ManyToManyField(through='guia_servs_clima.OrganizacaoTipoPagamento', to='guia_servs_clima.TipoPagamento'),
        ),
        migrations.AlterField(
            model_name='organizacao',
            name='tipos_produto',
            field=models.ManyToManyField(through='guia_servs_clima.OrganizacaoTipoProduto', to='guia_servs_clima.TipoProduto'),
        ),
    ]
