# Generated by Django 3.1.7 on 2021-09-13 18:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('guia_servs_clima', '0005_auto_20210817_1710'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='setoreconomico',
            options={'ordering': ['pk'], 'verbose_name': 'Setor Econômico', 'verbose_name_plural': 'Setores Econômicos'},
        ),
        migrations.AlterModelOptions(
            name='tipoorganizacao',
            options={'ordering': ['pk'], 'verbose_name': 'Tipo de Organização', 'verbose_name_plural': 'Tipos de Organização'},
        ),
    ]
