# Generated by Django 3.1.7 on 2021-09-24 18:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('municipios', '0001_initial'),
        ('guia_servs_clima', '0007_create_extension_unaccent'),
    ]

    operations = [
        migrations.CreateModel(
            name='MunicipioOrdenado',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('municipios.municipio',),
        ),
    ]
