# Generated by Django 3.1.7 on 2021-09-27 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guia_servs_clima', '0008_municipioordenado'),
    ]

    operations = [
        migrations.AddField(
            model_name='organizacao',
            name='politica_dados',
            field=models.BooleanField(blank=True, default=False, verbose_name='Termo de Politica de Dados'),
        ),
    ]
