# Generated by Django 3.1.7 on 2021-10-01 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guia_servs_clima', '0009_organizacao_politica_dados'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='organizacao',
            name='politica_dados',
        ),
        migrations.AddField(
            model_name='organizacao',
            name='politica_privacidade',
            field=models.BooleanField(blank=True, default=False, verbose_name='Política de Privacidade'),
        ),
        migrations.AddField(
            model_name='organizacao',
            name='termo_uso',
            field=models.BooleanField(blank=True, default=False, verbose_name='Termo de Uso'),
        ),
        migrations.AlterField(
            model_name='organizacao',
            name='natureza_organizacao',
            field=models.SmallIntegerField(choices=[(1, 'Pública'), (2, 'Privada'), (3, 'Público-Privada'), (4, 'Não Governamental'), (5, 'Profissional Autônomo')], verbose_name='Natureza da Organização'),
        ),
    ]
