# Generated by Django 3.1.7 on 2021-10-06 14:38

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('guia_servs_clima', '0010_auto_20211001_1619'),
    ]

    operations = [
        migrations.AddField(
            model_name='organizacao',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='organizacao',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
