# Generated by Django 3.1.7 on 2021-10-27 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guia_servs_clima', '0012_auto_20211006_1142'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organizacao',
            name='website_organizacao',
            field=models.CharField(blank=True, max_length=100, verbose_name='Site da Organização'),
        ),
    ]
