# Generated by Django 3.1.7 on 2021-11-18 13:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('guia_servs_clima', '0013_auto_20211027_1030'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tipopagamento',
            old_name='tipo_pagamento',
            new_name='nome',
        ),
    ]
